baseURL: https://tilman151.github.io
languageCode: en-us
title: Don't Repeat Yourself
theme: "PaperMod"

params:
    title: Don't Repeat Yourself
    description: The blog of Tilman Krokotsch

    homeInfoParams:
        Title: Hi, I'm Tilman
        Content: PhD & Machine Learning Engineer with a passion for software engineering. On this personal blog I will write about machine learning and coding topics that keep me up at night.

    DateFormat: "2 January 2006"
        
    socialIcons:
        - name: email
          url: "mailto:blog(at)krokotsch.eu"
        - name: github
          url: "https://github.com/tilman151"
        - name: linkedin
          url: "https://www.linkedin.com/in/tilman-krokotsch"


    assets:
        favicon: "/img/favicon.ico"
        favicon16x16:  "/img/favicon-16x16.png"
        favicon32x32:  "/img/favicon-32x32.png"
        apple_touch_icon:  "/img/apple-touch-icon.png"
        safari_pinned_tab:  "/img/safari-pinned-tab.svg"
    
    ShowReadingTime: true

menu:
  main:
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 10

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote: true